version: '3'

services:
  web:
    build: ./web
    environment:
      - APACHE_RUN_USER=www-data
    volumes:
        - ${APP_PATH_HOST}:${APP_PATH_CONRAINER}
    ports:
        - 8080:80
    working_dir: ${APP_PATH_CONRAINER}

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: laravelpass
    volumes:
    - ${DB_PATH_HOST}:${DB_PATH_CONRAINER}

  adminer:
    image: adminer
    restart: always
    ports:
    - 6080:8080

  composer:
    image: composer:1.6
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONRAINER}
    working_dir: ${APP_PATH_CONRAINER}
    command: composer install
